export const MIN_RECORDED_STT_DURATION_MS = 300;
export const MIN_RECORDED_STT_BYTES = 512;
export const MICROPHONE_PERMISSION_TIMEOUT_MS = 6_000;
export const ESCAPE_REWARD_DELAY_MS = 350;
export const REPLY_BUSY_GATE_MS = 700;
export const REPLY_PLAYBACK_END_GRACE_MS = 1_000;
export const REPLY_PLAYBACK_WATCHDOG_MS = 120_000;
export const REPLY_AUDIO_ARM_MS = 45_000;
