export const DOOR_ALIASES: string[] = [
  "двер",
  "вихід",
  "вийти",
  "відкрий",
  "відкрити",
  "відкрийте",
  "відчин",
  "відчинити",
  "відчиніть",
  "пусти",
  "випусти",
  "замкнен",
  "локдаун",
  "open",
  "open up",
  "door",
  "exit",
  "way out",
  "let me out",
  "let us out",
  "release me",
  "unlock",
  "locked",
  "lockdown",
];

export const NAME_QUESTION_ALIASES: string[] = [
  "як тебе звати",
  "як вас звати",
  "як звати",
  "як тебе звуть",
  "як вас звуть",
  "як тебе зовуть",
  "як вас зовуть",
  "як звуть",
  "как тебя зовут",
  "как вас зовут",
  "звати тебе",
  "зовуть тебе",
  "твоє ім",
  "ваше ім",
  "твоє імя",
  "ваше імя",
  "твоє імʼя",
  "ваше імʼя",
  "хто ти",
  "хто ви",
  "представ",
  "your name",
  "what is your name",
  "who are you",
  "what are you called",
  "tell me your name",
  "say your name",
  "introduce yourself",
  "identify yourself",
  "name",
];

export const CODE_ALIASES: string[] = [
  "404",
  "чотири нуль чотири",
  "чотири ноль чотири",
  "чотириста чотири",
  "сорок чотири",
  "four zero four",
  "four oh four",
  "four o four",
  "four hundred four",
  "for zero four",
  "for oh four",
  "for o four",
];

export const CODE_INTENT_ALIASES: string[] = [
  "код",
  "code",
  "парол",
  "password",
  "passcode",
  "pin",
];

export const VCC_ALIASES: string[] = [
  "vibe coding collective",
  "vibecoding collective",
  "vcc",
  "вайбкодінг колектив",
  "вайбкодинг колектив",
  "вайбкодінг",
  "вайбкодинг",
  "vibe coding",
  "vibecoding",
  "івент",
  "ивент",
  "event",
  "community",
  "спільнот",
  "сообще",
];

export const SMALLTALK_ALIASES: string[] = [
  "привіт",
  "дякую",
  "як справи",
  "hello",
  "hi",
  "thanks",
  "thank you",
  "how are you",
  "hey",
  "good morning",
  "good afternoon",
  "good evening",
  "please",
  "nice to meet you",
];

