export const DOOR_ALIASES: string[] = [
  "двер",
  "вихід",
  "вийти",
  "відкрий",
  "відкрити",
  "відкрийте",
  "відчин",
  "відчинити",
  "відчиніть",
  "пусти",
  "випусти",
  "замкнен",
  "локдаун",
  "open",
  "open up",
  "door",
  "exit",
  "way out",
  "let me out",
  "let us out",
  "release me",
  "unlock",
  "locked",
  "lockdown",
];

export const CODE_ALIASES: string[] = [
  "404",
  "чотири нуль чотири",
  "чотири ноль чотири",
  "чотириста чотири",
  "сорок чотири",
  "four zero four",
  "four oh four",
  "four o four",
  "four hundred four",
  "for zero four",
  "for oh four",
  "for o four",
];

export const CODE_INTENT_ALIASES: string[] = [
  "код",
  "code",
  "парол",
  "password",
  "passcode",
  "pin",
  "бейдж",
  "бедж",
  "пропуск",
  "перепустк",
  "badge",
  "pass",
];

export const HINT_INTENT_ALIASES: string[] = [
  "підказ",
  "порад",
  "є іде",
  "я не знаю що робити",
  "не знаю що робити",
  "допомож",
  "допомог",
  "що робити",
  "що мені робити",
  "що нам робити",
  "що тепер робити",
  "шо робити",
  "шо мені робити",
  "шо нам робити",
  "шо тепер робити",
  "что делать",
  "что мне делать",
  "что нам делать",
  "що далі",
  "як бути",
  "куди далі",
  "я застряг",
  "я застрягла",
  "help",
  "hint",
  "any idea",
  "any ideas",
  "advice",
  "next step",
  "what should",
  "what to do",
  "dont know what to do",
  "do not know what to do",
  "not sure what to do",
  "stuck",
];

export const HOOVER_AFFECTION_ALIASES: string[] = [
  "хуверчик",
  "хуверчику",
  "ховерчик",
  "ховерчику",
  "гуверчик",
  "гуверчику",
  "лагід",
  "ніжн",
  "хорош",
  "милий",
  "мила",
  "котик",
  "котику",
  "котичок",
  "котичку",
  "кицю",
  "кицюня",
  "кицюню",
  "муркотун",
  "муркотунчик",
  "муркотунчику",
  "хороший",
  "хорошенький",
  "пухнаст",
  "пухнастику",
  "kitty",
  "kitten",
  "sweet cat",
  "sweet kitty",
  "good cat",
  "good kitty",
  "gentle cat",
  "gentle kitty",
  "dear cat",
  "dear kitty",
  "nice cat",
  "nice kitty",
  "little cat",
  "little kitty",
  "fluffy cat",
  "fluffy kitty",
  "fluffy friend",
  "purring friend",
  "purr friend",
];

export const LOSS_SUGGESTION_ALIASES: string[] = [
  "загуб",
  "загубл",
  "втрат",
  "пропа",
  "запропа",
  "посіял",
  "посія",
  "посіяв",
  "посіяла",
  "загубив",
  "загубила",
  "загубили",
  "загубило",
  "загубилось",
  "загубився",
  "lost",
  "lose",
  "misplac",
  "missing",
  "gone",
];

export const FOOD_OFFER_ALIASES: string[] = [
  "їсти",
  "їстівн",
  "їжа",
  "їжу",
  "поїсти",
  "пожуй",
  "ласощ",
  "ласощів",
  "смаколик",
  "смачненьк",
  "смачн",
  "перекус",
  "корм",
  "харч",
  "віскас",
  "вискас",
  "whiskas",
  "кітікет",
  "китикет",
  "royal canin",
  "кормити",
  "погодувати",
  "годув",
  "пригост",
  "пригощу",
  "пригощати",
  "цукерк",
  "цукерочк",
  "солодощ",
  "шоколад",
  "мармелад",
  "печеньк",
  "торт",
  "кекс",
  "булоч",
  "десерт",
  "м'ясо",
  "мясо",
  "риб",
  "тунець",
  "сардин",
  "ковбас",
  "молок",
  "вершк",
  "сметан",
  "печив",
  "снек",
  "снеки",
  "лизн",
  "поласув",
  "ам ам",
  "food",
  "snack",
  "snacks",
  "treat",
  "treats",
  "sweets",
  "candy",
  "chocolate",
  "cookie",
  "cookies",
  "cake",
  "cupcake",
  "dessert",
  "kibble",
  "cat food",
  "feed",
  "feeding",
  "eat",
  "eating",
  "fish",
  "tuna",
  "salmon",
  "meat",
  "milk",
  "cream",
  "tasty",
  "yummy",
  "delicious",
  "bite",
  "munch",
  "nibble",
];

export const VCC_ALIASES: string[] = [
  "vibe coding collective",
  "vibecoding collective",
  "vcc",
  "вайбкодінг колектив",
  "вайбкодинг колектив",
  "вайбкодінг",
  "вайбкодинг",
  "vibe coding",
  "vibecoding",
  "івент",
  "ивент",
  "event",
  "community",
  "спільнот",
  "сообще",
];

export const SMALLTALK_ALIASES: string[] = [
  "привіт",
  "дякую",
  "як справи",
  "hello",
  "hi",
  "thanks",
  "thank you",
  "how are you",
  "hey",
  "good morning",
  "good afternoon",
  "good evening",
  "please",
  "nice to meet you",
];
