export function getRoutingContractBlock(): string {
  return [
    "[Routing contract]",
    "- Decide semantically who the player is addressing. Do not rely on exact",
    "  keyword matches when intent is clear.",
    "- Choose exactly one transitionId from allowedTransitions.",
    "- Choose actor from that transition's allowedActors, or its actor field if",
    "  allowedActors is absent.",
    "- Progress wins over chitchat when the transcript clearly satisfies a legal",
    "  progression transition.",
    "- Do not invent state fields. The backend computes next state after",
    "  validating your JSON.",
    "",
    "First-turn intro",
    "  - When allowedTransitions contains only sofia-introduced, that is the",
    "    only legal choice, regardless of who the player addressed or what",
    "    they asked. Actor must be sofia. nameTagActors must include sofia",
    "    and dan.",
    "",
    "Sofiia routing",
    "  - No clear addressee -> chitchat-replied with actor=sofia.",
    "  - Direct Sofiia address + semantic ask for an idea, hint, help, advice,",
    "    direction, or next step -> sofia-hint-given.",
    "  - Direct Sofiia address without asking for help -> chitchat-replied with",
    "    actor=sofia.",
    "  - Help requested without addressing Sofiia -> do not use sofia-hint-given.",
    "",
    "Dan routing",
    "  - Dan's dialogue is split into two phases.",
    "  - Phase 1 (danExplainedDoor is false): direct Dan address + intent",
    "    about the door, exit, code, badge, or how to get out ->",
    "    dan-explained-door. Dan explains he had a badge with the code but",
    "    can't find it. He does NOT mention the cat in phase 1.",
    "  - Phase 2 (danExplainedDoor is true, danBadgeAsked is false):",
    "    direct Dan address + a follow-up about the badge — where, when,",
    "    who, maybe a cat — > dan-badge-asked. Dan now mentions the white",
    "    cat was around the whole time. Even a short follow-up like \"де?\"",
    "    or \"a maybe a cat?\" counts here, because the conversation is",
    "    contextually about the badge.",
    "  - Direct Dan address without that intent (general chitchat, event,",
    "    vibe coding) -> chitchat-replied with actor=dan. Dan must not",
    "    raise the badge or door himself in that reply.",
    "  - Direct Dan address + revealed code 404 -> door-opened if legal.",
    "",
    "Hoover routing",
    "  - Direct Hoover address after Dan's clue + gentle wording ->",
    "    hoover-clue-given.",
    "  - Direct Hoover address after Dan's clue without gentle wording ->",
    "    hoover-ordinary-rejected.",
    "  - Direct Hoover address BEFORE Dan's clue (danBadgeAsked is false) ->",
    "    chitchat-replied with actor=sofia (the cat does not speak yet).",
    "",
    "Fixel routing",
    "  - Direct Fixel address after Hoover's clue + plausible waking attempt ->",
    "    code-revealed.",
    "  - Direct Fixel address after Hoover's clue without waking attempt ->",
    "    fixel-sleeping-rejected.",
    "  - Direct Fixel address BEFORE Hoover's clue (hooverClueGiven is false)",
    "    -> chitchat-replied with actor=sofia (the cat does not speak yet).",
  ].join("\n");
}
